### ISSUE TITLE
PWA status: Lighthouse could not determine if there was a service worker. 

### ISSUE THREAD

**Issue by philipbrembeck** [frontendnetwork/veganify#44]
Lighthouse does not find the serviceworker anymore (although it is recognized by chrome canary) and therefore displays no install promt on android devices anymore. 

- [x] https://github.com/GoogleChrome/lighthouse/issues/13396

**Comment by philipbrembeck** [comment]
Seems to be a problem in Canary Lighthouse: [#13396](https://github.com/GoogleChrome/lighthouse/issues/13396)

'sw.js' and initalizer work as expected - iOS is not affected from install popup not working.

**Comment by gitgauner** [comment]
I've encountered a few bugs while using Lambdatest (Google Pixel 4A, Android 11.0).
It seems to be that no "Install app"-prompt is displayed on android phones at all (tested with several real devices). Afaik this was a thing before, wasn't it? Installing as an app works fine. 

Quick video: ![image](https://user-images.githubusercontent.com/4144601/144582266-cc0c763c-8e9d-4522-8d88-79cd39f00b22.gif)

**Comment by philipbrembeck** [comment]
https://github.com/GoogleChrome/lighthouse/issues/13138

**Comment by gitgauner** [comment]
The fix was apparently merged and released, although the above mentioned issues are not closed atm. 

Lighthouse however throws no errors anymore, and the Install app prompt is available again:

<img width="500" alt="Bildschirmfoto 2021-12-19 um 15 38 42" src="https://user-images.githubusercontent.com/87610380/146678982-03d4de5b-a9cf-4cb1-addb-9bb60acea43d.png">

Tested with Chrome on Google Pixel 4A, Android 11.0. Firefox testing will follow and I'll reopen the issue if anything does not work correctly. 

Until then: Fixed.
