### ISSUE TITLE
Integrate is-vegan API if brocade.io is used

### ISSUE THREAD

**Issue by gitgauner** [frontendnetwork/veganify#82]
Integrate [hmontazeri/is-vegan](https://github.com/hmontazeri/is-vegan) if Brocade.io is used

- [x] Test integration 
   - [x] Find matching if-cause (Only when Ingredients are provided)
   - [x] Add is-vegan API
   - [x] Test on test server (min. 50 products)
- [x] Git Push
- [x] Productive Integration

**Comment by philipbrembeck** [comment]
There are not many products with ingredients listed on brocade, but here's an example: [Nutella](https://www.brocade.io/api/items/00009800895007) 
````
$ curl https://www.brocade.io/api/items/00009800895007 
````

Formatted answer: 
````json
{
   "gtin14":"00009800895007",
   "brand_name":"Ferrero",
   "name":"Nutella",
   "fat":"12.0",
   "size":"13 oz",
   "fiber":"1",
   "sodium":"15",
   "sugars":"21",
   "protein":"2",
   "calories":"200",
   "trans_fat":"0.0",
   "cholesterol":"5",
   "ingredients":"Sugar, Palm Oil, Hazelnuts, Cocoa, Skim Milk, Whey, Lecithin, Vanillin",
   "carbohydrate":"23",
   "fat_calories":"110",
   "serving_size":"37g",
   "saturated_fat":"4.0",
   "servings_per_container":"10"
}
````

If we took the ingredient list from the API call and directly called the is-vegan API it would look something like this (using `rawurlencode()` in php:

````
$ curl https://is-vegan.netlify.app/.netlify/functions/api?ingredients=Sugar,%20Palm%20Oil,%20Hazelnuts,%20Cocoa,%20Skim%20Milk,%20Whey,%20Lecithin,%20Vanillin
````

resulting in (formatted):

````json
{
   "checkedIngredients":[
      "Sugar",
      " Palm Oil",
      " Hazelnuts",
      " Cocoa",
      " Skim Milk",
      " Whey",
      " Lecithin",
      " Vanillin"
   ],
   "isVeganSafe":false,
   "isVeganResult":{
      "nonvegan":[
         " Skim Milk",
         " Whey"
      ],
      "flagged":[
         " Lecithin"
      ]
   }
}
````

This would work for foods at least, but the is-vegan API seems to respond kind of slow especially with a larger list of ingredients, we'll need to test if it's acceptable or too slow.
Otherwise we should fork the project and host the API ourselves.

**Comment by philipbrembeck** [comment]
Not in OFF but in brocade with ingredients!: 00011194296452

**Comment by philipbrembeck** [comment]
With ingredients in brocade but not in OFF: 00011194360535
